### PR TITLE
Added more missing structs for jaylib...

### PR DESCRIPTION
**Pull request by Rabios**
Since time jaylib have problems with define Rectangle struct (Due to being not defined) which fixed, But later some structs had same problem, So i did my job and implemented them (And if anything missing i'll make sure to add it...)

### CODE REVIEW

**Review by electronstudio — CHANGES_REQUESTED** [review]
The changes to README require JDK 11, it won’t work on JDK 8. Please revert  changes to README.

**Comment by Rabios** [comment]
@electronstudio Wait, Can't JDK 8 run JAR with class directly?!

**Comment by Rabios** [comment]
Oh my...

**Comment by Rabios** [comment]
Done, Think you can merge it now right?

**Comment by electronstudio** [comment]
Thanks

**Pull request merged**
